### ISSUE TITLE
Indexing logs vague RuntimeError which results in error return code

### ISSUE THREAD

**Issue by b1r3k** [karlicoss/promnesia#338]
Indexing logs vague error which results in error return code of process and this breaks further handling. Any idea how to debug it further to understand why it's complaining about norm_url?

I'm using environment as described by https://github.com/b1r3k/docker-promnesia/blob/master/Dockerfile

```
│ [INFO    2022-11-05 06:01:22 promnesia dump.py:96] updated database "/data/promnesia.sqlite". 180444 total (180443  │
│ OK, 1 ERRORS, 180444 cleared, +-1 more)                                                                             │
│ [ERROR   2022-11-05 06:01:22 promnesia __main__.py:99] 1 errors, printing them out:                                 │
│ [ERROR   2022-11-05 06:01:22 promnesia __main__.py:101]     'RuntimeError' object has no attribute 'norm_url'       │
│ [ERROR   2022-11-05 06:01:22 promnesia __main__.py:102] 1 errors, exit code 1
```

**Comment by karlicoss** [comment]
Hey, thanks for reporting! 
I think latest version of promnesia prints exception info properly (as of https://github.com/karlicoss/promnesia/pull/334)
Can you try setting `PROMNESIA_VERSION` to `master` in the dockerfile and try again? Then it should should exact location where the error happened

**Comment by b1r3k** [comment]
Confirmed to work on version v1.1.20230129
