### ISSUE TITLE
tzlocal: issue getting local time zone

### ISSUE THREAD

**Issue by purarue** [karlicoss/promnesia#253]
Hmm, seems to be related to recent tzlocal changes?

On:

```
$ pip list | grep tzlocal
tzlocal                   4.0.1
```

(`setup.py` here only specifies `>=3.0`)

Running promnesia (anything), I get:

```
$ promnesia
[ERROR   2021-10-20 06:44:39 promnesia common.py:493] '_PytzShimTimezone' object has no attribute 'key'
    Traceback (most recent call last):
      File "/home/sean/Repos/promnesia-fork/src/promnesia/common.py", line 491, in get_system_zone
        return tzlocal.get_localzone().key # type: ignore[attr-defined] # mypy stubs aren't aware of api change yet (see https://github.com/python/typeshed/issues/6038)
    AttributeError: '_PytzShimTimezone' object has no attribute 'key'
```

```python
In [9]: tzlocal.get_localzone()
Out[9]: _PytzShimTimezone(zoneinfo.ZoneInfo(key='America/Los_Angeles'), 'America/Los_Angeles')

In [10]: tzlocal.get_localzone()._key
Out[10]: 'America/Los_Angeles'

In [11]: tzlocal.get_localzone().zone
<ipython-input-11-4cdf1d77a83c>:1: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  tzlocal.get_localzone().zone
Out[11]: 'America/Los_Angeles'
```

See [tzlocal repo](https://github.com/regebro/tzlocal), has a paragraph describing the changes

So I would guess this works with tzlocal 3.0, but doesn't with 4.0?

I think on 4.0, ones meant to do:

```python
tzlocal.get_localzone_name()
Out[13]: 'America/Los_Angeles'
```

**Comment by karlicoss** [comment]
lol, so yeah funny enough with version 4.0 the old way (`.zone`) works (so one solution would be to revert https://github.com/karlicoss/promnesia/commit/bc9d9034aa7d83c12e24c60aac50c965513ef9ae )
wonder what's up with these api changes :thinking:  

I think I'll just make it defensive and unpin the `>=3.0` requirement... annoying if someone has to upgrade it just for promnesia and ends up with conflicting versions

**Comment by purarue** [comment]
It seems that a lot of the functionality that pytz has provided python libs for years has been added to the stdlib in 3.9, which means lots of libraries have been trying to switch over? which results in this strange ripple effect of breaking changes

Is pretty well described by:

https://www.python.org/dev/peps/pep-0615/

https://pytz-deprecation-shim.readthedocs.io/en/latest/

https://docs.python.org/3/library/zoneinfo.html

**Comment by karlicoss** [comment]
Yep, I just found this issue https://github.com/regebro/tzlocal/issues/117, and the author describes what happened in great detail! 
Seems that this enough to support the 4.0 and 2.0 way, and version 3.0 is kinda broken anyway.
